// Auto-generated by Supabase CLI — do not edit manually.
// Run: pnpm supabase gen types typescript --local > packages/types/src/database/index.ts
// This file is populated in Phase 2 after migrations are applied.
export type Database = Record<string, unknown>;
