// Mobile route path constants — avoids typos in router.push() calls.
export const MOBILE_ROUTES = {
  LOGIN: '/(auth)/login',
  REGISTER: '/(auth)/register',
  FORGOT_PASSWORD: '/(auth)/forgot-password',
  DASHBOARD: '/(app)/(tabs)/dashboard',
  DISCOVER: '/(app)/(tabs)/discover',
  NOTIFICATIONS: '/(app)/(tabs)/notifications',
  PROFILE_TAB: '/(app)/(tabs)/profile',
  COMPETITION: (id: string) => `/(app)/competitions/${id}` as const,
  COMPETITION_FEED: (id: string) => `/(app)/competitions/${id}/feed` as const,
  COMPETITION_LEADERBOARD: (id: string) => `/(app)/competitions/${id}/leaderboard` as const,
  COMPETITION_EVENTS: (id: string) => `/(app)/competitions/${id}/events` as const,
  COMPETITION_CHAT: (id: string) => `/(app)/competitions/${id}/chat` as const,
  COMPETITION_MEMBERS: (id: string) => `/(app)/competitions/${id}/members` as const,
  COMPETITION_SETTINGS: (id: string) => `/(app)/competitions/${id}/settings` as const,
  COMPETITION_PODIUM: (id: string) => `/(app)/competitions/${id}/podium` as const,
  EVENT_DETAIL: (compId: string, eventId: string) =>
    `/(app)/competitions/${compId}/events/${eventId}` as const,
  PROFILE: (id: string) => `/(app)/profile/${id}` as const,
  MESSAGES: '/(app)/messages',
  MESSAGE_THREAD: (conversationId: string) => `/(app)/messages/${conversationId}` as const,
  CLAIM: (ghostProfileId: string) => `/(app)/claim/${ghostProfileId}` as const,
  MODAL_CREATE_COMPETITION: '/(app)/modals/create-competition',
  MODAL_JOIN_COMPETITION: '/(app)/modals/join-competition',
  MODAL_SUBMIT_RESULT: '/(app)/modals/submit-result',
  MODAL_ADD_EVENT: '/(app)/modals/add-event',
  MODAL_TIEBREAKER: '/(app)/modals/tiebreaker',
} as const;
